# This script is loaded onto the pi pico using the thonny IDE

import machine
import time
import sys

led_pin = machine.Pin(25, machine.Pin.OUT)
gpio_pin_0 = machine.Pin(0, machine.Pin.OUT)
gpio_pin_1 = machine.Pin(1, machine.Pin.OUT)
gpio_pin_2 = machine.Pin(2, machine.Pin.OUT)
gpio_pin_3 = machine.Pin(3, machine.Pin.OUT)
gpio_pin_4 = machine.Pin(4, machine.Pin.OUT)
gpio_pin_5 = machine.Pin(5, machine.Pin.OUT)
gpio_pin_6 = machine.Pin(6, machine.Pin.OUT)
gpio_pin_7 = machine.Pin(7, machine.Pin.OUT)
gpio_pin_8 = machine.Pin(8, machine.Pin.OUT)
gpio_pin_9 = machine.Pin(9, machine.Pin.OUT)
gpio_pin_10 = machine.Pin(10, machine.Pin.OUT)
gpio_pin_11 = machine.Pin(11, machine.Pin.OUT)
gpio_pin_12 = machine.Pin(12, machine.Pin.OUT)
gpio_pin_13 = machine.Pin(13, machine.Pin.OUT)
gpio_pin_14 = machine.Pin(14, machine.Pin.OUT)
gpio_pin_15 = machine.Pin(15, machine.Pin.OUT)


def process_command(command):
    """Processes serial commands and takes actions."""
    command = command.strip()
    if command == "scope1_0":
        gpio_pin_0.value(0)
        gpio_pin_1.value(0)
        gpio_pin_2.value(0)
        gpio_pin_3.value(0)
        gpio_pin_4.value(0)
        print("scope1_0")
    elif command == "scope1_1":
        gpio_pin_0.value(1)
        gpio_pin_1.value(0)
        gpio_pin_2.value(0)
        gpio_pin_3.value(0)
        gpio_pin_4.value(0)
        print("scope1_1")
    elif command == "scope1_2":
        gpio_pin_0.value(0)
        gpio_pin_1.value(1)
        gpio_pin_2.value(0)
        gpio_pin_3.value(0)
        gpio_pin_4.value(0)
        print("scope1_2")
    elif command == "scope1_3":
        gpio_pin_0.value(1)
        gpio_pin_1.value(1)
        gpio_pin_2.value(0)
        gpio_pin_3.value(0)
        gpio_pin_4.value(0)
        print("scope1_3")
    elif command == "scope1_4":
        gpio_pin_0.value(0)
        gpio_pin_1.value(0)
        gpio_pin_2.value(1)
        gpio_pin_3.value(0)
        gpio_pin_4.value(0)
        print("scope1_4")
    elif command == "scope1_5":
        gpio_pin_0.value(1)
        gpio_pin_1.value(0)
        gpio_pin_2.value(1)
        gpio_pin_3.value(0)
        gpio_pin_4.value(0)
        print("scope1_5")
    elif command == "scope1_6":
        gpio_pin_0.value(0)
        gpio_pin_1.value(1)
        gpio_pin_2.value(1)
        gpio_pin_3.value(0)
        gpio_pin_4.value(0)
        print("scope1_6")
    elif command == "scope1_7":
        gpio_pin_0.value(1)
        gpio_pin_1.value(1)
        gpio_pin_2.value(1)
        gpio_pin_3.value(0)
        gpio_pin_4.value(0)
        print("scope1_7")
    elif command == "scope1_8":
        gpio_pin_0.value(0)
        gpio_pin_1.value(0)
        gpio_pin_2.value(0)
        gpio_pin_3.value(1)
        gpio_pin_4.value(0)
        print("scope1_8")
    elif command == "scope1_9":
        gpio_pin_0.value(1)
        gpio_pin_1.value(0)
        gpio_pin_2.value(0)
        gpio_pin_3.value(1)
        gpio_pin_4.value(0)
        print("scope1_9")
    elif command == "scope1_10":
        gpio_pin_0.value(0)
        gpio_pin_1.value(1)
        gpio_pin_2.value(0)
        gpio_pin_3.value(1)
        gpio_pin_4.value(0)
        print("scope1_10")
    elif command == "scope1_11":
        gpio_pin_0.value(1)
        gpio_pin_1.value(1)
        gpio_pin_2.value(0)
        gpio_pin_3.value(1)
        gpio_pin_4.value(0)
        print("scope1_11")
    elif command == "scope1_12":
        gpio_pin_0.value(0)
        gpio_pin_1.value(0)
        gpio_pin_2.value(1)
        gpio_pin_3.value(1)
        gpio_pin_4.value(0)
        print("scope1_12")
    elif command == "scope1_13":
        gpio_pin_0.value(1)
        gpio_pin_1.value(0)
        gpio_pin_2.value(1)
        gpio_pin_3.value(1)
        gpio_pin_4.value(0)
        print("scope1_13")
    elif command == "scope1_14":
        gpio_pin_0.value(0)
        gpio_pin_1.value(1)
        gpio_pin_2.value(1)
        gpio_pin_3.value(1)
        gpio_pin_4.value(0)
        print("scope1_14")
    elif command == "scope1_15":
        gpio_pin_0.value(1)
        gpio_pin_1.value(1)
        gpio_pin_2.value(1)
        gpio_pin_3.value(1)
        gpio_pin_4.value(0)
        print("scope1_15")
    elif command == "scope1_16":
        gpio_pin_0.value(0)
        gpio_pin_1.value(0)
        gpio_pin_2.value(0)
        gpio_pin_3.value(0)
        gpio_pin_4.value(1)
        print("scope1_16")
    elif command == "scope1_17":
        gpio_pin_0.value(1)
        gpio_pin_1.value(0)
        gpio_pin_2.value(0)
        gpio_pin_3.value(0)
        gpio_pin_4.value(1)
        print("scope1_17")
    elif command == "scope1_18":
        gpio_pin_0.value(0)
        gpio_pin_1.value(1)
        gpio_pin_2.value(0)
        gpio_pin_3.value(0)
        gpio_pin_4.value(1)
        print("scope1_18")
    elif command == "scope1_19":
        gpio_pin_0.value(1)
        gpio_pin_1.value(1)
        gpio_pin_2.value(0)
        gpio_pin_3.value(0)
        gpio_pin_4.value(1)
        print("scope1_19")
    elif command == "scope1_20":
        gpio_pin_0.value(0)
        gpio_pin_1.value(0)
        gpio_pin_2.value(1)
        gpio_pin_3.value(0)
        gpio_pin_4.value(1)
        print("scope1_20")
    elif command == "scope1_21":
        gpio_pin_0.value(1)
        gpio_pin_1.value(0)
        gpio_pin_2.value(1)
        gpio_pin_3.value(0)
        gpio_pin_4.value(1)
        print("scope1_21")
    elif command == "scope1_22":
        gpio_pin_0.value(0)
        gpio_pin_1.value(1)
        gpio_pin_2.value(1)
        gpio_pin_3.value(0)
        gpio_pin_4.value(1)
        print("scope1_22")
    elif command == "scope1_23":
        gpio_pin_0.value(1)
        gpio_pin_1.value(1)
        gpio_pin_2.value(1)
        gpio_pin_3.value(0)
        gpio_pin_4.value(1)
        print("scope1_23")
    elif command == "scope1_24":
        gpio_pin_0.value(0)
        gpio_pin_1.value(0)
        gpio_pin_2.value(0)
        gpio_pin_3.value(1)
        gpio_pin_4.value(1)
        print("scope1_24")
    elif command == "scope1_25":
        gpio_pin_0.value(1)
        gpio_pin_1.value(0)
        gpio_pin_2.value(0)
        gpio_pin_3.value(1)
        gpio_pin_4.value(1)
        print("scope1_25")
    elif command == "scope1_26":
        gpio_pin_0.value(0)
        gpio_pin_1.value(1)
        gpio_pin_2.value(0)
        gpio_pin_3.value(1)
        gpio_pin_4.value(1)
        print("scope1_26")
    elif command == "scope1_27":
        gpio_pin_0.value(1)
        gpio_pin_1.value(1)
        gpio_pin_2.value(0)
        gpio_pin_3.value(1)
        gpio_pin_4.value(1)
        print("scope1_27")
    elif command == "scope1_28":
        gpio_pin_0.value(0)
        gpio_pin_1.value(0)
        gpio_pin_2.value(1)
        gpio_pin_3.value(1)
        gpio_pin_4.value(1)
        print("scope1_28")
    elif command == "scope1_29":
        gpio_pin_0.value(1)
        gpio_pin_1.value(0)
        gpio_pin_2.value(1)
        gpio_pin_3.value(1)
        gpio_pin_4.value(1)
        print("scope1_29")
    elif command == "scope1_30":
        gpio_pin_0.value(0)
        gpio_pin_1.value(1)
        gpio_pin_2.value(1)
        gpio_pin_3.value(1)
        gpio_pin_4.value(1)
        print("scope1_30")
    elif command == "scope1_31":
        gpio_pin_0.value(1)
        gpio_pin_1.value(1)
        gpio_pin_2.value(1)
        gpio_pin_3.value(1)
        gpio_pin_4.value(1)
        print("scope1_31")
        #------------------------------------------------
    elif command == "scope2_0":
        gpio_pin_5.value(0)
        gpio_pin_6.value(0)
        gpio_pin_7.value(0)
        gpio_pin_8.value(0)
        gpio_pin_9.value(0)
        print("scope2_0")
    elif command == "scope2_1":
        gpio_pin_5.value(0)
        gpio_pin_6.value(1)
        gpio_pin_7.value(0)
        gpio_pin_8.value(0)
        gpio_pin_9.value(0)
        print("scope2_1")
    elif command == "scope2_2":
        gpio_pin_5.value(0)
        gpio_pin_6.value(1)
        gpio_pin_7.value(0)
        gpio_pin_8.value(0)
        gpio_pin_9.value(0)
        print("scope2_2")
    elif command == "scope2_3":
        gpio_pin_5.value(1)
        gpio_pin_6.value(1)
        gpio_pin_7.value(0)
        gpio_pin_8.value(0)
        gpio_pin_9.value(0)
        print("scope2_3")
    elif command == "scope2_4":
        gpio_pin_5.value(0)
        gpio_pin_6.value(0)
        gpio_pin_7.value(1)
        gpio_pin_8.value(0)
        gpio_pin_9.value(0)
        print("scope2_4")
    elif command == "scope2_5":
        gpio_pin_5.value(1)
        gpio_pin_6.value(0)
        gpio_pin_7.value(1)
        gpio_pin_8.value(0)
        gpio_pin_9.value(0)
        print("scope2_5")
    elif command == "scope2_6":
        gpio_pin_5.value(0)
        gpio_pin_6.value(1)
        gpio_pin_7.value(1)
        gpio_pin_8.value(0)
        gpio_pin_9.value(0)
        print("scope2_6")
    elif command == "scope2_7":
        gpio_pin_5.value(1)
        gpio_pin_6.value(1)
        gpio_pin_7.value(1)
        gpio_pin_8.value(0)
        gpio_pin_9.value(0)
        print("scope2_7")
    elif command == "scope2_8":
        gpio_pin_5.value(0)
        gpio_pin_6.value(0)
        gpio_pin_7.value(0)
        gpio_pin_8.value(1)
        gpio_pin_9.value(0)
        print("scope2_8")
    elif command == "scope2_9":
        gpio_pin_5.value(1)
        gpio_pin_6.value(0)
        gpio_pin_7.value(0)
        gpio_pin_8.value(1)
        gpio_pin_9.value(0)
        print("scope2_9")
    elif command == "scope2_10":
        gpio_pin_5.value(0)
        gpio_pin_6.value(1)
        gpio_pin_7.value(0)
        gpio_pin_8.value(1)
        gpio_pin_9.value(0)
        print("scope2_10")
    elif command == "scope2_11":
        gpio_pin_5.value(1)
        gpio_pin_6.value(1)
        gpio_pin_7.value(0)
        gpio_pin_8.value(1)
        gpio_pin_9.value(0)
        print("scope2_11")
    elif command == "scope2_12":
        gpio_pin_5.value(0)
        gpio_pin_6.value(0)
        gpio_pin_7.value(1)
        gpio_pin_8.value(1)
        gpio_pin_9.value(0)
        print("scope2_12")
    elif command == "scope2_13":
        gpio_pin_5.value(1)
        gpio_pin_6.value(0)
        gpio_pin_7.value(1)
        gpio_pin_8.value(1)
        gpio_pin_9.value(0)
        print("scope2_13")
    elif command == "scope2_14":
        gpio_pin_5.value(0)
        gpio_pin_6.value(1)
        gpio_pin_7.value(1)
        gpio_pin_8.value(1)
        gpio_pin_9.value(0)
        print("scope2_14")
    elif command == "scope2_15":
        gpio_pin_5.value(1)
        gpio_pin_6.value(1)
        gpio_pin_7.value(1)
        gpio_pin_8.value(1)
        gpio_pin_9.value(0)
        print("scope2_15")
    elif command == "scope2_16":
        gpio_pin_5.value(0)
        gpio_pin_6.value(0)
        gpio_pin_7.value(0)
        gpio_pin_8.value(0)
        gpio_pin_9.value(1)
        print("scope2_16")
    elif command == "scope2_17":
        gpio_pin_5.value(1)
        gpio_pin_6.value(0)
        gpio_pin_7.value(0)
        gpio_pin_8.value(0)
        gpio_pin_9.value(1)
        print("scope2_17")
    elif command == "scope2_18":
        gpio_pin_5.value(0)
        gpio_pin_6.value(1)
        gpio_pin_7.value(0)
        gpio_pin_8.value(0)
        gpio_pin_9.value(1)
        print("scope2_18")
    elif command == "scope2_19":
        gpio_pin_5.value(1)
        gpio_pin_6.value(1)
        gpio_pin_7.value(0)
        gpio_pin_8.value(0)
        gpio_pin_9.value(1)
        print("scope2_19")
    elif command == "scope2_20":
        gpio_pin_5.value(0)
        gpio_pin_6.value(0)
        gpio_pin_7.value(1)
        gpio_pin_8.value(0)
        gpio_pin_9.value(1)
        print("scope2_20")
    elif command == "scope2_21":
        gpio_pin_5.value(1)
        gpio_pin_6.value(0)
        gpio_pin_7.value(1)
        gpio_pin_8.value(0)
        gpio_pin_9.value(1)
        print("scope2_21")
    elif command == "scope2_22":
        gpio_pin_5.value(0)
        gpio_pin_6.value(1)
        gpio_pin_7.value(1)
        gpio_pin_8.value(0)
        gpio_pin_9.value(1)
        print("scope2_22")
    elif command == "scope2_23":
        gpio_pin_5.value(1)
        gpio_pin_6.value(1)
        gpio_pin_7.value(1)
        gpio_pin_8.value(0)
        gpio_pin_9.value(1)
        print("scope2_23")
    elif command == "scope2_24":
        gpio_pin_5.value(0)
        gpio_pin_6.value(0)
        gpio_pin_7.value(0)
        gpio_pin_8.value(1)
        gpio_pin_9.value(1)
        print("scope2_24")
    elif command == "scope2_25":
        gpio_pin_5.value(1)
        gpio_pin_6.value(0)
        gpio_pin_7.value(0)
        gpio_pin_8.value(1)
        gpio_pin_9.value(1)
        print("scope2_25")
    elif command == "scope2_26":
        gpio_pin_5.value(0)
        gpio_pin_6.value(1)
        gpio_pin_7.value(0)
        gpio_pin_8.value(1)
        gpio_pin_9.value(1)
        print("scope2_26")
    elif command == "scope2_27":
        gpio_pin_5.value(1)
        gpio_pin_6.value(1)
        gpio_pin_7.value(0)
        gpio_pin_8.value(1)
        gpio_pin_9.value(1)
        print("scope2_27")
    elif command == "scope2_28":
        gpio_pin_5.value(0)
        gpio_pin_6.value(0)
        gpio_pin_7.value(1)
        gpio_pin_8.value(1)
        gpio_pin_9.value(1)
        print("scope2_28")
    elif command == "scope2_29":
        gpio_pin_5.value(1)
        gpio_pin_6.value(0)
        gpio_pin_7.value(1)
        gpio_pin_8.value(1)
        gpio_pin_9.value(1)
        print("scope2_29")
    elif command == "scope2_30":
        gpio_pin_5.value(0)
        gpio_pin_6.value(1)
        gpio_pin_7.value(1)
        gpio_pin_8.value(1)
        gpio_pin_9.value(1)
        print("scope2_30")
    elif command == "scope2_31":
        gpio_pin_5.value(1)
        gpio_pin_6.value(1)
        gpio_pin_7.value(1)
        gpio_pin_8.value(1)
        gpio_pin_9.value(1)
        print("scope2_31")

        print("scope2_15")#---------------------------------------------------
    elif command == "wave1_0":
        gpio_pin_10.value(0)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_0")
    elif command == "wave1_1":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_1")
    elif command == "wave1_2":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_2")
    elif command == "wave1_3":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_3")
    elif command == "wave1_4":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_4")
    elif command == "wave1_5":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_5")
    elif command == "wave1_6":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_6")
    elif command == "wave1_7":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_7")
    elif command == "wave1_8":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_8")
    elif command == "wave1_9":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_9")
    elif command == "wave1_10":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_10")
    elif command == "wave1_11":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_11")
    elif command == "wave1_12":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_12")
    elif command == "wave1_13":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_13")
    elif command == "wave1_14":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_14")
    elif command == "wave1_15":
        gpio_pin_10.value(1)
        gpio_pin_11.value(0)
        gpio_pin_12.value(0)
        gpio_pin_13.value(0)
        gpio_pin_14.value(0)
        print("wave1_15")      
    else:
        print(f"Unknown command: {command} (local)")

while True:
    led_pin.value(1)
    command = sys.stdin.readline().strip()
    process_command(command)
    time.sleep_ms(100)
